name: docs
on:
  push:
    branches:
      - main

jobs:
    docs:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Setup Node.js
          uses: actions/setup-node@v2
          with:
            node-version: '20.x'
        - name: Install dependencies
          run: npm install
        - name: Build
          run: npm run docs:build
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs/.vuepress/dist
            publish_branch: gh-pages
        